const fantasyDeck = [
  { number: 1, name: 'Wizard', type: 'Character' },
  { number: 2, name: 'Dragon', type: 'Character' },
  { number: 3, name: 'Ruler of the Kingdom', type: 'Character' },
  { number: 4, name: 'Artifact', type: 'Item' },
  { number: 5, name: 'Fae', type: 'Character' },
  { number: 6, name: 'Shapeshift', type: 'Aspect' },
  { number: 7, name: 'Prince', type: 'Character' },
  { number: 8, name: 'Magical', type: 'Aspect' },
  { number: 9, name: 'Adventurer', type: 'Character' },
  { number: 10, name: 'Witch', type: 'Character' },
  { number: 11, name: 'Most Desirous', type: 'Aspect' },
  { number: 12, name: 'Step-Mother', type: 'Character' },
  { number: 13, name: 'Knight', type: 'Character' },
  { number: 14, name: 'Princess', type: 'Character' },
  { number: 15, name: 'Cursed', type: 'Aspect' },
  { number: 16, name: 'Chosen of the Prophecy', type: 'Aspect' },
  { number: 17, name: 'Unicorn', type: 'Character' },
  { number: 18, name: 'Fairy God Relative', type: 'Character' },
  { number: 19, name: 'Squire', type: 'Character' },
  { number: 20, name: 'Reviled', type: 'Aspect' },
  { number: 21, name: 'Marriage', type: 'Event' },
  { number: 22, name: 'Coming of Age', type: 'Event' },
  { number: 23, name: 'Sword', type: 'Item' },
  { number: 24, name: 'Crystal', type: 'Item' },
  { number: 25, name: 'Tome', type: 'Item' },
  { number: 26, name: 'Death', type: 'Event' },
  { number: 27, name: 'Falling in Love', type: 'Event' },
  { number: 28, name: 'Fight', type: 'Event' },
  { number: 29, name: 'Birth', type: 'Event' },
  { number: 30, name: 'Scroll', type: 'Item' },
  { number: 31, name: 'Wand', type: 'Item' },
  { number: 32, name: 'Coin', type: 'Item' },
  { number: 33, name: 'Villager', type: 'Character' },
  { number: 34, name: 'Castle', type: 'Place' },
  { number: 35, name: 'Village', type: 'Place' },
  { number: 36, name: 'Forest', type: 'Place' },
  { number: 37, name: 'Dungeon', type: 'Place' },
  { number: 38, name: 'Golden rays', type: 'Detail' },
  { number: 39, name: 'Sparkling', type: 'Detail' },
  { number: 40, name: 'The Stars', type: 'Detail' },
];

export default fantasyDeck;
